In [1]:
import pandas as pd
import oracledb
from sqlalchemy import create_engine
oracle_conn = create_engine("oracle+oracledb://system:admin@localhost:1521/xe")
pd.read_sql("""select * from employees""",oracle_conn)

    empid          empname department   salary  managerid joiningdate
0       1     Anjali Mehta      Sales  68000.0        NaN  2020-03-15
1       2      Rahul Singh  Marketing   1000.0        1.0  2019-06-01
2       3        Meera Das         HR  50000.0        1.0  2021-01-20
3       4       Vikram Rao         IT  85000.0        2.0  2018-07-10
4       5       Priya Iyer      Sales  60000.0        2.0  2022-02-11
5       6       Arjun Nair         IT  95000.0        4.0  2017-09-05
6       7     Suresh Patil    Finance  78000.0        1.0  2019-12-01
7       8      Neha Kapoor  Marketing  67000.0        2.0  2021-03-22
8       9       Amit Verma      Sales  72000.0        5.0  2018-11-15
9      10      Kavya Reddy         IT  88000.0        4.0  2020-08-17
10     11      Rohan Gupta    Finance  64000.0        7.0  2021-06-05
11     12     Pooja Sharma         HR  55000.0        3.0  2022-07-11
12     13     Deepak Joshi         IT  91000.0        6.0  2019-09-23
13     14     Shalini Nair  Marketing  76000.0        2.0  2018-01-29
14     15     Mohit Bansal      Sales  59000.0        9.0  2020-10-09
15     16       Isha Menon    Finance  82000.0        7.0  2017-04-14
16     17     Varun Khanna         IT  97000.0        6.0  2016-12-30
17     18    Tanvi Agarwal         HR  53000.0        3.0  2021-11-19
18     19     Aditya Desai      Sales  61000.0        5.0  2019-02-07
19     20  Ritika Malhotra  Marketing  70000.0       14.0  2022-05-13

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:oracle.oracledb